language: node_js
node_js:
  - "10"
before_install:
  - openssl aes-256-cbc -K $encrypted_fdbc054559ab_key -iv $encrypted_fdbc054559ab_iv
    -in ./gcloud/vibage-stage-cred.json.enc -out ./keys/vibage-stage-cred.json -d
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: gae
  keyfile: "./keys/vibage-stage-cred.json"
  project: vibage-stage
  config: "./gcloud/stage.app.yml"
  on: stage
